language: python

python: 
  - "2.6"
  - "2.7"
  - "3.2"
  
install:
    - pip install git+https://github.com/NeuralEnsemble/libNeuroML.git@development
    - python setup.py install
    
script:
    - pynml -h
    - ./test.sh
